### ISSUE TITLE
Network: Player class shouldn’t include network related code.

### ISSUE THREAD

**Issue by filfat** [JSPrismarine/JSPrismarine#100]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2420%20Funded-%2300A156.svg" />](https://issuehunt.io/r/JSPrismarine/JSPrismarine/issues/100)

The player (and in turn entity) class should only contain functionality related to the player/entity.

Just like in PM3, having network code there can and will cause issues in the future. We should instead adopt the same principles as in PM4 and separate it.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $20.00)

- [<img src='https://avatars1.githubusercontent.com/u/1370209?v=4' alt='filfat' width=24 height=24> filfat](https://issuehunt.io/u/filfat) ($20.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/JSPrismarine/JSPrismarine/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by HerryYT** [comment]
We can make a class for example PlayerConnection that has all network functionalities
