### ISSUE TITLE
RFC: TelemetryManager.

### ISSUE THREAD

**Issue by filfat** [JSPrismarine/JSPrismarine#123]
# RFC
### Introduction
As JSPrismarine grows it'll be more and more valuable to have a centralized repository with server telemetry data, crashlogs and general statistics. Since privacy is extremely important we'll need to be completely transparent, and anonymize every instance of JSPrismarine.

### Implementation
We should have a general TelemetryManager that respects both the `enable-telemetry` & `telemetry-url` config options.

##### `private void sendHeartBeat(void)`
This function will run at least every 5 minutes and send the following as a json object to `telemetry-url`/api/heartbeat:
* `id` See `generateAnonomizedId`.
* `version` The current JSPrismarine version and git revision as `VERSION:GIT_REV`.
* `online_mode` If the server requires Xbox authentication or not.
* `player_count` Current player count.
* `max_player_count` Max player count.
* `plugins` Array of plugin `name` and `version`.
* `tps` Current ticks per second.
* `uptime` Server uptime in seconds.
* `node_env` Set to either `production` or `development` depending on the current `process.end.NODE_ENV`.

##### `public void sendCrashLog(crashlog: string)`
This function will be invoked upon a complete server crash and will send an anonymized crashlog (see `generateAnonomizedCrashLog`), anonymized server id (see `generateAnonomizedId`) (before this is possible we'll need to hook into `uncaughtException` in `./src/server.ts`).

##### `public string generateAnonomizedId(void)`
Returns a hashed string of the systems MAC address.
##### `private string generateAnonomizedCrashLog(crashlog: string)`
This should remove any references to
* IP addresses.
* MAC addresses.
* Player names.
* Chat messages.
* Directory listings (above the JSPrismarine folder).
* Any other privacy compromising data not specified above.

**Comment by filfat** [comment]
It might even make sense to have the `telemetry-url` be an array of URLs in case a server network wants to have their own instance of the telemetry server while also contributing valuable data to the project.

**Comment by filfat** [comment]
It might also make sense to store a `telemetry-salt` in the config and use that with `generateAnonomizedId ` to prevent people from brute forcing whatever we end up using to generate the ID.

**Comment by Bavfalcon9** [comment]
I like the idea of this as it makes it easier for us to track errors, however I think it should run on server crashes as well, meaning hook into `process.on('unhandledRejection')`

**Comment by filfat** [comment]
> I like the idea of this as it makes it easier for us to track errors, however I think it should run on server crashes as well, meaning hook into `process.on('unhandledRejection')`

Yes, I actually specified that in `sendCrashLog`.

**Comment by Bavfalcon9** [comment]
Oh I somehow missed that, sorry ;-;

**Comment by HerryYT** [comment]
I really like the idea but to make the unique id I would use something like: https://www.npmjs.com/package/node-machine-id

**Comment by filfat** [comment]
> I really like the idea but to make the unique id I would use something like: https://www.npmjs.com/package/node-machine-id

That’s way better!
