### ISSUE TITLE
What do you expect to be waiting for when awaiting evt.post() ? 

### ISSUE THREAD

**Issue by garronej** [JSPrismarine/JSPrismarine#158]
Hi @filfat,

In [src/Prismarine.ts](https://github.com/JSPrismarine/JSPrismarine/blob/master/src/Prismarine.ts) what do you expect
when awating this post? 

![image](https://user-images.githubusercontent.com/6702424/97085297-fa598c00-161c-11eb-9ee3-276cfbc977f3.png)

Let's say for example I have this scenario:

```typescript
const em = new EventManager(null as any);

em.on('playerConnect', async () => {

    await new Promise(resolve=> setTimeout(resolve, 100));

    console.log("bar");

});

console.log("foo");

await em.emit('playerConnect', null as any);

console.log("baz");
```

Do you expect `foo bar baz` to be printed in the console? 
Because currently it would be `foo baz bar`.

I can make the `EventManager` behave the way you want it to but I just want to make sure what it is you want exactly. 😊 

Cheers

**Comment by filfat** [comment]
Hey!

Yes, `foo bar baz` would be the preferred output. We can't however assume that each event has something attached to it (since some event would only be used by a plugin). :)

**Comment by garronej** [comment]
Yes sure sure.
I mean what you want `EventManager.prototype.emit()` to return is a promise that resolve after all the asynchronous handler have resolved. 

I can implement that in. As a matter of fact I may make that the default behaviour in Evt `3.0`. If would be a much more usefull returned value that the curren 'number of handlers invoked'

**Comment by filfat** [comment]
> I mean what you want EventManager.prototype.emit() to return is a promise that resolve after all the asynchronous handler 

Yeah, I think that would be great!
