### ISSUE TITLE
Bug: Grey particles when breaking grass.

### ISSUE THREAD

**Issue by xvdg06** [JSPrismarine/JSPrismarine#18]
![image](https://user-images.githubusercontent.com/61436375/89710233-f51f6600-d978-11ea-95f3-1380c8533f66.png)

**expected result:**
When the block breaks, the correct particles should show (like in singleplayer, green)

**What actually happens:**
Grey particles (that appear to have the wrong texture) show

**How to reproduce this bug:**
- Break a block

**Comment by nougator** [comment]
This isn't implemented yet if I'm not wrong.

**Comment by Ian-Yy** [comment]
Hello, can I try look into this?

**Comment by HerryYT** [comment]
> Hello, can I try look into this?

That's fine! 👍 (afaik it should be related to runtime IDs)

**Comment by Ian-Yy** [comment]
@HerryYT Thanks for the direction. I'm kinda new at this.

**Comment by Ian-Yy** [comment]
Hi @HerryYT. Currently I am following the readme to install but I am hitting this issue when I do `npm run build`

```bash
src/prismarine.ts:70:53 - error TS2345: Argument of type 'World | null' is not assignable to parameter of type 'World'.
  Type 'null' is not assignable to type 'World'.

70                     connection, connection.address, world, this
                                                       ~~~~~
Found 1 error.
```

Here is my version of nodejs and npm
nodejs - v14.14.0
npm - 6.14.8

**Comment by HerryYT** [comment]
@Ian-Yy Fixed #115 👍 let me know

**Comment by Ian-Yy** [comment]
Thanks. Its fixed.

**Comment by Ian-Yy** [comment]
Hi @HerryYT, I have created a PR. Please review and correct me if I am wrong and need changes. Thank you.

**Comment by filfat** [comment]
While the update block packet resolves this we still need to implement runtime IDs before it’s actually fixed.

**Comment by filfat** [comment]
> Hi @HerryYT, I have created a PR. Please review and correct me if I am wrong and need changes. Thank you.

Please join the discord! :))

**Comment by Ian-Yy** [comment]
Sorry, I thought the runtime IDs is the block runtime IDs. So what do I actually need to do with the runtime IDs? And I have joined the discord. =D

**Comment by Ian-Yy** [comment]
@filfat. Do you mind explaining more about the runtime IDs?

**Comment by Bavfalcon9** [comment]
Runtime ids are a map of what blocks are registered on the server (during runtime), to the client. These ids are sent to the client in `StartGame` and the server is expected to maintain them. Think of it as an interface to the client and server telling the client what "runtimeID" is what block.

**Comment by Ian-Yy** [comment]
Alright cool! So, what do you mean by implementing runtime IDs? If it's already there during `StartGame` packet.

**Comment by filfat** [comment]
@Ian-Yy we haven’t implemented NBT writing yet, so the palette of block ids we’re sending in `StartGame` are incorrect. As soon as that’s resolved this will automatically also be resolved (that will also fix the block update setting the block to a nether fence instead of air).

**Comment by Ian-Yy** [comment]
Wow. That sounds very complicated and interesting at the same time. But is someone doing it? Cause I might need guidance if required to do that.

**Comment by Bavfalcon9** [comment]
I'll find a way to implement this in my TS PR.
