### ISSUE TITLE
Performance: Investigate possible benefits of using bytenode.

### ISSUE THREAD

**Issue by filiphsandstrom** [JSPrismarine/JSPrismarine#274]
From what I can gather [bytenode](https://github.com/OsamaAbbas/bytenode) improves performance a little bit by pre-compiling the code into v8 bytecode.  This also has the side-effect of making the actual binary smaller.

**Comment by Bavfalcon9** [comment]
Possibility of using WASM as well.

**Comment by Bavfalcon9** [comment]
Just spent an hour trying to get bytenode to work, ran into multiple issues, such as not being able to compile a directory and when I made a script for it, I got "exports not found" from bytenode. If anyone else wants to try this feel free xd

**Comment by filfat** [comment]
> Just spent an hour trying to get bytenode to work, ran into multiple issues, such as not being able to compile a directory and when I made a script for it, I got "exports not found" from bytenode. If anyone else wants to try this feel free xd

I've gotten it to work previously, but it's not really that important before at least `v0.2.0`.
