### ISSUE TITLE
Bug: put / remove the block

### ISSUE THREAD

**Issue by rfrizov** [JSPrismarine/JSPrismarine#281]
Hello. When you try to put a block, it is not put, the server freezes, and further attempts to enter end in failure.

Console error: ****[error]: Handler error inventorytransactionpacket-handler: (Error: Invalid inventorytransactiontype)****

After that, attempts to log in to the server fail. When entering, there is also an error:

****[error]: Handler error ServerSettingsRequestPacket-handler: (Error: Missing handler for packet 0x66)****

Version: 1.16.201 (protocol: 422)

**Comment by filfat** [comment]
I can't reproduce this. Which device are you using to connect to the server?

**Comment by rfrizov** [comment]
I use: Samsung Galaxy M21

**Comment by filfat** [comment]
> I use: Samsung Galaxy M21

Can you try again on the latest commit. Also can you include the `JSPrismarine.log` file if it still fails.

**Comment by rfrizov** [comment]
> > I use: Samsung Galaxy M21
> 
> Can you try again on the latest commit. Also can you include the `JSPrismarine.log` file if it still fails.

I take it this was fixed in the last commit?

**Comment by filfat** [comment]
> > > I use: Samsung Galaxy M21
> > 
> > 
> > Can you try again on the latest commit. Also can you include the `JSPrismarine.log` file if it still fails.
> 
> I take it this was fixed in the last commit?

It might be.

**Comment by filfat** [comment]
Still can't recreate it. Please reopen the issue if it still occurs!
