### ISSUE TITLE
Permissions 

### ISSUE THREAD

**Issue by ConnorHopper** [JSPrismarine/JSPrismarine#324]
**Describe the bug**
Some commands (/gamemode) arent registered.

**To Reproduce**
Clone the git (I used Windows Git).
npm install
npm run build
npm run start

**Screenshots**
![image](https://user-images.githubusercontent.com/68204085/104243268-51a61600-542e-11eb-97f6-5548bd0b39e9.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Node: [14.15]

**Comment by filfat** [comment]
@ConnorHopper can you upload the prismarine.log file to a gist and link it here?

**Comment by filfat** [comment]
I'm still interested in the `prismarine.log` file. This issue can probably be resolved just by deleting the `dist` folder and re-building. I've also added an extra safe-guard. Let me know if this still occurs.
