### ISSUE TITLE
Bug: Colored concrete doesn't show up

### ISSUE THREAD

**Issue by Jakobg1215** [JSPrismarine/JSPrismarine#331]
White concrete shows up but the other colors don't.

![Minecraft 1_14_2021 8_48_37 AM](https://user-images.githubusercontent.com/74737820/104606399-54c71f00-5645-11eb-8976-3abd431c392c.png)

[jsprismarine.log](https://github.com/JSPrismarine/JSPrismarine/files/5815124/jsprismarine.log)

**Comment by filfat** [comment]
This is probably related to the legacyId/runtimeId mapper. We have similar problems with non-registered blocks showing up.
