### ISSUE TITLE
Command Handler (Discussion): Possible Refactor

### ISSUE THREAD

**Issue by john-bv** [JSPrismarine/JSPrismarine#334]
**Why refactor?**
This is probably going to be the most frequent question to this issue, so I'm going to try and answer this as brief as possible. The new arg parser (https://github.com/JSPrismarine/JSPrismarine/pull/308) Is fairly verbose in terms of creating commands and is frustrating to work with. Refactoring would be able to give the community an opportunity to refactor the api to a more user friendly alternative that is fun and easy to use.

## Current arg parser
**Pros:**
 - Uses the exact ported version of the vanilla argument parsing
 - Allows easier implementation for descriptive arguments.
 - Allows precision argument parsing.
 
**Cons:**
 - Very verbose api
 - Not very user friendly
 - Callback/Promise hell
 
 *(I tried to be neutral when making this list)*
 
 **Why I believe this implementation should change:**
 Personally, I don't like callback hell based api's, they are very frustrating to work with and we can still achieve a very vanilla like  experience without a vanilla implementation. I believe a more class based approach to this would be better, as well as a class based argument parser. 
 
 **So what solution do I propose?**
 In pseudo code I believe something like the following (concept) with a little more thought would be a more direct, less verbose and more user friendly api to work with:
 ```ts
class StringArg extends Argument {
     public resolve(source: CommandExecuter, argument: string, additionalargs: string[]): string | void {
          this.consumes('all'); // consumes all additional arguments
          return additionalargs.slice(-1).join(' ');
     }
}
class NonVanillaSayCommand extends Command {
     public constructor() {
          super('name', 'description', ['aliases']);
          this.arguments.add(0, new StringArg('message'));
     }

     public onRun(executer: CommandExecuter, args: Argument[], stringArgs: string[]): boolean {
          return executer.send(args[0]);
     }
}
```

**Comment by TheArmagan** [comment]
Fliph: https://www.youtube.com/watch?v=qWwb8S02f_c

**Comment by Bavfalcon9** [comment]
Please see: #351 for general api implementation.
