### ISSUE TITLE
Block/Test: Make sure we don’t have multiple blocks with the same id.

### ISSUE THREAD

**Issue by filfat** [JSPrismarine/JSPrismarine#342]
This will prevent issues like the one we had with terracotta/concrete.

**Comment by greyliances** [comment]
Namespace rather. The ID would obviously be the same for any blocks that share the same ID such as Wool, Wood, Carpets, Fences, Stained Glass etc. iirc Bedrock already has unique Namespaces for all blocks which would be a much better indicator for Dupes

**Comment by filfat** [comment]
> Namespace rather. The ID would obviously be the same for any blocks that share the same ID such as Wool, Wood, Carpets, Fences, Stained Glass etc. iirc Bedrock already has unique Namespaces for all blocks which would be a much better indicator for Dupes

Yes. When saying `id` I'm referring to the `namespaced IDs` otherwise I would've said `numeric IDs`.
