### ISSUE TITLE
Bug: error 404 for plugins

### ISSUE THREAD

**Issue by Jakobg1215** [JSPrismarine/JSPrismarine#357]
Getting a 404 error code when using my plugin

[plugin code](https://github.com/Jakobg1215/friend-ship)

![JSPrismarine - Visual Studio Code 1_19_2021 12_13_10 PM](https://user-images.githubusercontent.com/74737820/105075718-c04b2b00-5a4f-11eb-9352-f81af3573404.png)

[jsprismarine.log](https://github.com/JSPrismarine/JSPrismarine/files/5837757/jsprismarine.log)

**Comment by Bavfalcon9** [comment]
You can not depend on `@jsprismarine/prismarine` as a dependency, it should be included as a dev-dependency. 
This is will now throw an error in future versions of JSP. (Thanks @filfat)
