### ISSUE TITLE
Is there any documentation for the client package?

### ISSUE THREAD

**Issue by ScooScoot** [JSPrismarine/JSPrismarine#441]

**Comment by TobidieTopfpflanze** [comment]
The code is currently the "documentation".
JsPrismarine isn't production ready, yet. We are still changing a lot of things or rewrite them. It will take a while to get to the point to have good documentation.

However, [here](https://docs.prismarine.dev/) you can find our documentation about JsPrismarine.

**Comment by filiphsps** [comment]
https://docs.jsprismarine.org/ 🚀
