### ISSUE TITLE
Fix dependencies issues by releasing a new patch version

### ISSUE THREAD

**Issue by vincss** [JSPrismarine/JSPrismarine#701]
Hi !
First, thanks for the good work on this project !

I've got a small project that uses this one but only respond on client connections : 
https://github.com/vincss/mcsleepingserverstarter

I'm facing a small issue which is that the dependabot of github is creating security issue for this dependence.
Would it be possible to create a maintenance version with those dependencies updated ?
![image](https://user-images.githubusercontent.com/2254806/158136376-22495c5f-0b95-4935-ba60-e5c86b54f923.png)
![image](https://user-images.githubusercontent.com/2254806/158136419-e2219be4-acc2-4ac3-a9da-ea543df9beef.png)
![image](https://user-images.githubusercontent.com/2254806/158136457-379a5938-3f08-4497-8548-9680692c5032.png)

Thanks !

**Comment by filiphsps** [comment]
Sorry for the extremely late response. Just bumped the package to `0.1.0-rc.50`. Not sure if everything still works though (I mean there’s like 700 commits between releases and neither of us have really had time to maintain this). Let us know how it goes! 🤠

**Comment by vincss** [comment]
Hi,
When I try to update the package, I cannot build it : 
src/sleepingBedrock.ts:20:20 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider 
writing a dynamic 'import("@jsprismarine/prismarine/dist/config/Config")' call instead.

**Comment by filiphsps** [comment]
> Hi, Thanks for the release.
> 
> When I try to update the package, I cannot build it : src/sleepingBedrock.ts:20:20 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@jsprismarine/prismarine/dist/config/Config")' call instead.
> 
> I tried to update my project to esm, but there is so many issues when doing it.

Hi, thanks for letting me know! I’ll take a look as soon as I have a little free time. Missed this message so feel free to reach out on Discord or Twitter next time for a little more swift response :)
