### ISSUE TITLE
Commands: Handle multiple sets of arguments

### ISSUE THREAD

**Issue by filfat** [JSPrismarine/JSPrismarine#94]
currently we only support one set of arguments which causes problems with certain commands that have an array of different argument setups.

Take the `/tp` command.
It should support the following:
- `/tp <target> [x] [y] [z]`
- `/tp <target> <target>`
- etc

**Comment by TheArmagan** [comment]
i can make theese

**Comment by TheArmagan** [comment]
the vanilla commands

**Comment by filfat** [comment]
@TheArmagan I've implemented the base logic for it. You can check the TP command.

**Comment by TheArmagan** [comment]
sure!
